version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
    ports:
      - "5432:5432"
  app:
    build: ./
    container_name: "java-app"
    ports:
      - "8080:8080"
